# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('author_title', models.CharField(max_length=100)),
                ('author_image', models.URLField(blank=True, null=True)),
                ('author_page', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('category', models.CharField(max_length=40)),
                ('authors', models.ManyToManyField(to='core.Author')),
            ],
        ),
    ]
