# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170413_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='card',
            name='subtitle',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
