# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170427_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_credit',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
