# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_card_image_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image_credit',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
