# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170427_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='lede',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
