# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_card_lede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
