# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170502_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='lede',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='subtitle',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
