# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170502_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='lede',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
