# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170504_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(max_length=75, null=True),
        ),
    ]
