# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_card_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.SlugField(blank=True, max_length=75, null=True),
        ),
    ]
