# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170530_1726'),
        ('core', '0014_auto_20170526_1634'),
    ]

    operations = [
    ]
