# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20170530_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=40)),
                ('slug', models.SlugField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='themes',
            field=models.ManyToManyField(blank=True, to='core.Theme'),
        ),
    ]
